version: "3.3"
services:
  api:
    image: nestjs-test-task:latest
    container_name: nestjs-test-task
    restart: always
    env_file:
      - .env.prod
    networks:
      - fullnet
    ports:
      - "5005:7000"
    depends_on:
      - postgres

  postgres:
    container_name: nest_postgres
    image: postgres:alpine
    restart: always
    networks:
      - fullnet
    ports:
      - "5435:5432"
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - nestjs-postgres:/var/lib/postgresql/data
volumes:
  nestjs-postgres:

networks:
  fullnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"