version: "3.8"
services:
  api:
    image: nestjs-test-task:latest
    container_name: nestjs-test-task
    restart: always
    ports:
      - "5005:7000"
    volumes:
      - ./.env.prod:/opt/app/.env.prod
    depends_on:
      - postgres

  postgres:
    container_name: nest_postgres
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - nestjs-postgres:/var/lib/postgresql/data
volumes:
  nestjs-postgres: